services:
    App\Installer\:
        resource: '../Installer/*'
        exclude: '../Installer/{DependencyInjection,Entity,Migrations,Templates,Tests,DataFixtures}'

    App\Installer\Controller\:
        resource: '../Installer/Controller'
        tags: ['controller.service_arguments']

twig:
    paths:
        '%kernel.project_dir%/templates/%admin_theme%/pages/installer/': installer-admin

framework:
    translator:
        paths: ["%kernel.project_dir%/src/Installer/Translations"]
