services:
    App\Comment\:
        resource: '../Comment/*'
        exclude: '../Comment/{DependencyInjection,Entity,Migrations,Templates,Tests,DataFixtures}'

    App\Comment\Controller\:
        resource: '../Comment/Controller'
        tags: ['controller.service_arguments']

    App\Comment\Repository\:
        resource: '../Comment/Repository'
        autowire: true
        tags: ['doctrine.repository_service']

twig:
    paths:
        '%kernel.project_dir%/templates/%base_theme_folder%/pages/comment/': comment

framework:
    translator:
        paths: ["%kernel.project_dir%/src/Comment/Translations"]

doctrine:
    orm:
        auto_mapping: true
        mappings:
            Comment:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Comment/Entity'
                prefix: 'App\Comment\Entity'
                alias: Comment
