services:
    App\Formulario\:
        resource: '../Formulario/*'
        exclude: '../Formulario/{DependencyInjection,Entity,Migrations,Templates,Tests,DataFixtures}'

    App\Formulario\Controller\:
        resource: '../Formulario/Controller'
        tags: ['controller.service_arguments']

    App\Formulario\Repository\:
        resource: '../Formulario/Repository'
        autowire: true
        tags: ['doctrine.repository_service']

twig:
    paths:
        '%kernel.project_dir%/templates/%admin_theme%/pages/formulario/': formulario-admin

framework:
    translator:
        paths: ["%kernel.project_dir%/src/Formulario/Translations"]

doctrine:
    orm:
        auto_mapping: true
        mappings:
            FormModel:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Formulario/Entity'
                prefix: 'App\Formulario\Entity'
                alias: FormModel
