# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    locale: fr
    base_theme: liquid-theme
    admin_theme: liquid-admin-theme
    data_folder: Data
    homepage_path: /posts
    gmap_api: AIzaSyAadz2owJTc8CJnIkvzps2jgzQpnsnxdgA
    posts_templates:
      blocks/post/oldway_show_post.html.twig: oldway