# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    locale: fr
    appLocales: 'fr|en|es|pt|it|de|nl|pl|cs'
    appLocalesList: 
        fr: 'français'
        en: 'english'
        es: 'español'
        pt: 'português'
        it: 'italiano'
        de: 'deutsch'
        nl: 'dutch'
        pl: 'polskie'
        cd: 'čeština'
    base_theme: liquid-theme
    admin_theme: liquid-admin-theme
    data_folder: Data
    homepage_path: '/%kernel.default_locale%'
    gmap_api: AIzaSyAadz2owJTc8CJnIkvzps2jgzQpnsnxdgA
    posts_templates:
      blocks/post/oldway_show_post.html.twig: oldway