twig:
    paths:
        '%kernel.project_dir%/templates/liquid-admin-theme': liquid-theme

framework:
    translator:
        paths: ["%kernel.project_dir%/templates/liquid-theme/translations"]